version: 0.2

phases:
  install:
    runtime-versions:
     nodejs: 14
    commands:
    - echo update npm...
    - npm install -g n
    - n latest
    - npm update -g npm
    - node -v
    - npm -v

    - npm install -g yarn
    - yarn -v
    
  pre_build:
    commands:
      - npm install
      - yarn install
      - yarn add @slack/bolt
      - yarn add -D nodemon dotenv
    
  build:
    commands:    
      - echo Build started on `date`
      - ng build --prod
      - echo Running test...
      - echo starting...
      - yarn run build
  post_build:
    commands:
      - echo cp to s3
      - aws s3 sync . s3://pihlnikldevops --delete
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  discard-paths: yes
  name: build-$(date +%Y-%n-&d)
  base-directory: "."
